.PHONY: build test race vet format-check benchmark
build:
	go build ./cmd/...
test:
	go test ./...
race:
	go test -race ./...
vet:
	go vet ./...
format-check:
	@test -z "$$(gofmt -l cmd internal tests benchmarks)" || (gofmt -l cmd internal tests benchmarks && exit 1)
benchmark:
	go test -run '^$$' -bench=. -benchtime=100x -benchmem ./benchmarks
