apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ci-preview-platform.name" . }}
  labels:
    {{- include "ci-preview-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ci-preview-platform.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
