apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ci-preview-platform.name" . }}
  labels:
    {{- include "ci-preview-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
